### ISSUE TITLE
Not working with latest Emoncms?

### ISSUE THREAD

**Issue by bphermansson** [emoncms/packetgen#4]
I've installed this module via Git:

cd /var/www/html/emoncms/Modules
git clone https://github.com/emoncms/packetgen.git

I use a pre-configured img on a Raspberry Pi, version "low-write 9.7 | 2016.05.25".
I the go to Extra/RFM12b Packet generator and try to add a new variable, but nothing happens. I fill in a value, a type and an initial value before clicking "Add", but nothing. The packet size doesn't change, nothing reflects my addition. What can be wrong?

**Comment by glynhudson** [comment]
Sorry this module is not currently under development or support. 

I would recommend using MQTT, nodeRED, openHAB and Wifi control realy  to inform control systems and activate control. These are all built into the latest Raspberry Pi Emoncms image

https://github.com/openenergymonitor/emonpi/wiki/emonSD-pre-built-SD-card-Download-%26-Change-Log

https://guide.openenergymonitor.org/integrations/

**Comment by bphermansson** [comment]
Ok, I'll try that.

**Comment by bphermansson** [comment]
Maybe I can use the software RTC for Emonglcd instead, as described on https://openenergymonitor.org/emon/emonglcd?

**Comment by bphermansson** [comment]
Ok at last I tried to use the software RTC I mentioned above and it works.
